---
csharp:
    displayName: C#
    steps:
        - file: "csharp/Recordings/Program.cs"
          highlight: "0-193"
        - file: "csharp/Recordings/Program.cs"
          highlight: "24-32"
        - file: "csharp/Recordings/Program.cs"
          highlight: "36-38"
        - file: "csharp/Recordings/Program.cs"
          highlight: "185-191"
        - file: "csharp/Recordings/Program.cs"
          highlight: "40-67"
        - file: "csharp/Recordings/Program.cs"
          highlight: "84-99"
        - file: "csharp/Recordings/Program.cs"
          highlight: "107-122"
        - file: "csharp/Recordings/Program.cs"
          highlight: "130-144"
        - file: "csharp/Recordings/Program.cs"
          highlight: "164-177"
        - file: "csharp/Recordings/Program.cs"
          highlight: "151-157"
java:
    displayName: Java
    steps:
        - file: "java/src/main/java/Main.java"
          highlight: "0-214"
        - file: "java/src/main/java/Main.java"
          highlight: "24-32"
        - file: "java/src/main/java/Main.java"
          highlight: "36-41"
        - file: "java/src/main/java/Main.java"
          highlight: "178-213"
        - file: "java/src/main/java/Main.java"
          highlight: "43-67"
        - file: "java/src/main/java/Main.java"
          highlight: "81-95"
        - file: "java/src/main/java/Main.java"
          highlight: "103-114"
        - file: "java/src/main/java/Main.java"
          highlight: "122-140"
        - file: "java/src/main/java/Main.java"
          highlight: "161-170"
        - file: "java/src/main/java/Main.java"
          highlight: "148-154"